server:
  port: 5000

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=false
      database: travelgram
